apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-staging-ingress
spec:
  rules:
  - host: staging.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-staging-service
            port:
              number: 80
